version : 1

formatters:
  simpleFormatter:
    format : '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  fileHandler:
    formatter: simpleFormatter
    class : logging.handlers.RotatingFileHandler
    filename : 'logs/classification.log'
    backupCount : 10
    maxBytes : 20971520
    level : INFO
    encoding: utf-8

  consoleHandler:
    formatter: simpleFormatter
    class: logging.StreamHandler
    stream  : ext://sys.stdout
    level: INFO

root :
  handlers: [fileHandler, consoleHandler]
  level: DEBUG

disable_existing_loggers : false
