NeuralNetwork:
    enabled: True
    model_parameters:
        activation_function: relu
        units:
            - 100
            - 100
            - 100
    training_parameters:
        epochs: 50
        batch_size: 64
    name_parameters:
        folder_name: NeuralNetwork
        model_name: model_nn.keras

CNN:
    enabled: False
    model_parameters:
        activation_function: relu
        filters:
            - 128
            - 128
            - 128
        kernel_size: 3
        pool_size: 2
    training_parameters:
        epochs: 50
        batch_size: 64
    name_parameters:
        folder_name: ConvolutionalNeuronalNetwork
        model_name: model_CNN.keras

RNN:
    enabled: False
    model_parameters:
        activation_function: tanh
        hidden_units:
            - 128
            - 128
    training_parameters:
        epochs: 50
        batch_size: 64
    name_parameters:
        folder_name: RecurrentNeuronalNetwork
        model_name: model_RNN.keras

LSTM:
    enabled: False
    model_parameters:
        activation_function: tanh
        hidden_units:
            - 64
            - 64
    training_parameters:
        epochs: 50
        batch_size: 64
    name_parameters:
        folder_name: LongShortTermMemory
        model_name: model_LSTM.keras
